### ISSUE TITLE
Update outdated `cml publish` syntax

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/workshop-uncool-mlops#5]
As per https://github.com/iterative/cml/issues/1000#issuecomment-1124628318, `cml publish` no longer accepts piped data; please replace `vl2png ... | cml publish` by `vl2png ... > plot.png` and `cml publish plot.png`

#### [`workshop-uncool-mlops`](https://github.com/iterative/workshop-uncool-mlops)

* main — docs/3-online-reproducibility.md

#### [`workshop-uncool-mlops-solution`](https://github.com/iterative/workshop-uncool-mlops-solution)

- main — .github/workflows/on_pr.yml
- epochs-8 — .github/workflows/on_pr.yml
- train-epochs-10 — .github/workflows/on_pr.yml
- train-epochs-10 — README.md
- train-epochs-20 — .github/workflows/on_pr.yml
- train-epochs-20 — README.md
- update-until — .github/workflows/on_pr.yml

**Comment by daavoo** [comment]
Done
